apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      resources:
        limits: # soft limit
          memory: "128Mi" # RAM
          cpu: "100m" # CPU in milli units (100m = 0.1 CPU)
        requests: # hard limit
          memory: "64Mi"
          cpu: "250m"
