apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
  #namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:latest
      envFrom:
      - configMapRef:
          name: nginx-configmap
