apiVersion: v1
kind: service
metadata:
  name: nginx-service
spec:
  selecctor:
    project: roboshop
    environment: dev
    kubernetes: true
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
