apiVersion: v1
kind: service
metadata:
  name: nginx-service
spec:
  selector:
    project: roboshop
    environment: dev
    kubernetes: true
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
