apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    kubernetes: "true"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
