apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    project: roboshop
    environment: dev
spec:
  replicas: 3 # maintains 3 pods at all times
  selector:
    matchLabels:
      app: nginx # must match template labels below
      project: roboshop
      environment: dev
# Pod Definition
template:
  metadata:
    labels:
      app: nginx # must match selector above
      project: roboshop
      environment: dev
  spec:
    containers:
      - name: nginx
        image: nginx:1.25
        ports:
          - containerPort: 80
